version: '3.8'

services:
  express:
    image: node:14
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
    depends_on:
      - mysql

  mysql:
    image: mysql:9.1.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234qwer
      MYSQL_DATABASE: naran_development
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: